backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "/public/images/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "uploads"
publish_mode: editorial_workflow
local_backend: true

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"

collections:
  - name: "categorias" # Used in routes, e.g., /admin/collections/blog
    label: "Categorías" # Used in the UI
    editor:
      preview: false
    folder: "src/content/categorias" # The path to the folder where the documents are stored
    identifier_field: "titulo"
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    format: "json"
    sortable_fields: ["order", "titulo"] # Default is title:asc
    media_folder: "/public/images/uploads/categorias" # Media files will be stored in the repo under images/uploads
    public_folder: "uploads/categorias"
    fields: # The fields for each document, usually in front matter
      - {label: "Nombre", name: "titulo", widget: "string"}
      - {label: "Orden", name: "order", widget: "number"}
      - {label: "Color (HEX)", name: "color", widget: "string", default: "#00a1e4"}
      - {label: "Url", name: "url", widget: "string", required: false}
      - {label: "Imagen", name: "img", widget: "image"}

  - name: "profesores" # Used in routes, e.g., /admin/collections/blog
    label: "Profesores" # Used in the UI
    editor:
      preview: false
    folder: "src/content/profesores" # The path to the folder where the documents are stored
    identifier_field: "nombre"
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    format: "json"
    fields: # The fields for each document, usually in front matter
      - {label: "Nombre", name: "nombre", widget: "string"}
      - {label: "Ocupación", name: "ocupacion", widget: "string"}
      - {label: "Imagen", name: "thumbnail", widget: "image"}
      - label: "Programas"
        name: "programas"
        widget: "object"
        collapsed: false
        fields:
          - {label: "General", name: "general", widget: "boolean", default: true, required: false}
          - {label: "Young Entrepeneur", name: "young-entrepeneur", widget: "boolean", default: false, required: false}
          - {label: "Full Inclusion", name: "full-inclusion", widget: "boolean", default: false, required: false}
          - {label: "Young Leaders", name: "young-leaders", widget: "boolean", default: false, required: false}
          - {label: "Evolution", name: "evolution", widget: "boolean", default: false, required: false}

  - name: "testimonios" # Used in routes, e.g., /admin/collections/blog
    label: "Testimonios" # Used in the UI
    editor:
      preview: false
    folder: "src/content/testimonios" # The path to the folder where the documents are stored
    identifier_field: "autor"
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    format: "json"
    fields: # The fields for each document, usually in front matter
      - {label: "Cita", name: "cita", widget: "text"}
      - {label: "Autor", name: "autor", widget: "string"}
      - {label: "Imagen", name: "imagen", widget: "image"}

  - name: "talks" # Used in routes, e.g., /admin/collections/blog
    editor:
      preview: false
    label: "YES Talks" # Used in the UI
    folder: "src/pages/talks" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    preview_path: "talks/{{slug}}"
    format: "frontmatter"
    media_folder: "/public/images/uploads/talks/{{year}}-{{month}}-{{day}}-{{slug}}" # Media files will be stored in the repo under images/uploads
    public_folder: "uploads/talks/{{year}}-{{month}}-{{day}}-{{slug}}"
    sort: "date:desc" # Default is title:asc
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "talks"}
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Link del video (YouTube)", name: "video", widget: "string"}
      - {label: "Thumbnail", name: "thumbnail", widget: "image"}
      - {label: "Publish Date", name: "date", widget: "datetime", date_format: "DD/MM/YYYY", time_format: "HH:mm", picker_utc: true}
      - {label: "Sinopsis", name: "body", widget: "markdown"}

  - name: "packs" # Used in routes, e.g., /admin/collections/blog
    editor:
      preview: false
    label: "YES Packs" # Used in the UI
    folder: "src/content/packs" # The path to the folder where the documents are stored
    identifier_field: "mes"
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    preview_path: "packs"
    format: "json"
    media_folder: "/public/images/uploads/packs/{{slug}}" # Media files will be stored in the repo under images/uploads
    public_folder: "uploads/packs/{{slug}}"
    sort: "date:desc" # Default is title:asc
    summary: "{{mes}} - {{title}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Portada", name: "thumbnail", widget: "image"}
      - {label: "Fecha de publicación", name: "date", widget: "datetime", date_format: "DD/MM/YYYY", time_format: "HH:mm", picker_utc: true}
      - label: "Mes"
        name: "mes"
        widget: "select"
        options: ["Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"]
      - label: "Cursos"
        name: "cursos"
        widget: "list"
        min: 1
        fields:
          - {label: 'Slug del curso', name: slug, widget: string}
          - {label: Nombre, name: title, widget: string}
          - {label: Thumbnail, name: thumbnail, widget: image}
          - {label: Instructor, name: instructor, widget: string}
          - {label: 'Número de modulos', name: number, widget: string}

#  - name: "blog" # Used in routes, e.g., /admin/collections/blog
#    label: "Posts" # Used in the UI
#    folder: "src/pages/blog" # The path to the folder where the documents are stored
#    create: true # Allow users to create new documents in this collection
#    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
#    format: "frontmatter"
#    sort: "date:desc" # Default is title:asc
#    fields: # The fields for each document, usually in front matter
#      - {label: "Id", name: "id", widget: "hidden", default: "{{slug}}"}
#      - {label: "Title", name: "title", widget: "string"}
#      - {label: "Publish Date", name: "date", widget: "datetime", date_format: "DD/MM/YYYY", time_format: "HH:mm", picker_utc: true}
#      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
#      - {label: "Body", name: "body", widget: "markdown"}
